version: "3.3"

services:
  app:
    container_name: app
    build:
      context: .
    volumes:
      - ./:/usr/src
    ports:
      - "3000:3000"
      - "4000:4000"
    depends_on:
      - mongodb
    command: ["npm", "start"]

  mongodb:
    container_name: mongodb
    image: mongo
    ports:
      - "27017:27017"